// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package stockproducts

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	Uuid        pgtype.UUID
	Name        string
	Reference   string
	Line        string
	Supplier    string
	Description string
	ImageUrl    string
	Price       pgtype.Numeric
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type ProductVariant struct {
	Uuid        pgtype.UUID
	ProductUuid pgtype.UUID
	Name        string
	Reference   string
	Description string
	ImageUrl    string
	Price       pgtype.Numeric
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}
