// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package stockproducts

import (
	"context"
)

const listProducts = `-- name: ListProducts :many
SELECT uuid, name, reference, line, supplier, description, "image-url", price, "created-at", "updated-at" FROM "Products"
ORDER BY "updated-at" DESC
LIMIT $2 OFFSET (($1 - 1) * $2)
`

type ListProductsParams struct {
	Column1 interface{}
	Limit   int32
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.Uuid,
			&i.Name,
			&i.Reference,
			&i.Line,
			&i.Supplier,
			&i.Description,
			&i.ImageUrl,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
